grails-app/controllers/grails/plugins/springsocial/twitter/SpringSocialTwitterController.groovy
/* Copyright 2011 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package grails.plugins.springsocial.twitter

import org.springframework.social.twitter.api.Twitter

class SpringSocialTwitterController {

  def twitter
  def connectionRepository

  def beforeInterceptor = [action: this.&auth, except: 'login']

  def index = {
    def model = ["profile": twitter.userOperations().getUserProfile()]
    render(view: "/springsocial/twitter/index", model: model)
  }

  def timeline = {
    def id = params.id ?: "home"
    def tweets
    switch (id) {
      case "home":
        tweets = twitter.timelineOperations().getHomeTimeline()
        break
      case "user":
        tweets = twitter.timelineOperations().getUserTimeline()
        break
      case "public":
        tweets = twitter.timelineOperations().getPublicTimeline()
        break
      case "mentions":
        tweets = twitter.timelineOperations().getMentions()
        break
      case "favorites":
        tweets = twitter.timelineOperations().getFavorites()
        break
      default:
        tweets = twitter.timelineOperations().getHomeTimeline()
        break
    }

    render view: SpringSocialTwitterUtils.config.twitter.page.timeLine, model: ['timeline': tweets]

  }

  def profiles = {
    def id = params.id ?: "friends"
    def profiles
    switch (id) {
      case "friends":
        profiles = twitter.friendOperations().getFriends()
        break
      case "followers":
        profiles = twitter.friendOperations().getFollowers()
        break
      default:
        profiles = twitter.friendOperations().getFriends()
        break
    }
    render view: SpringSocialTwitterUtils.config.twitter.page.profiles, model: ['profiles': profiles]
  }

  def messages = {
    def dmListType = params.id ?: 'received'
    def directMessages
    switch (dmListType) {
      case 'received':
        directMessages = twitter.directMessageOperations().getDirectMessagesReceived()
        break
      case 'sent':
        directMessages = twitter.directMessageOperations().getDirectMessagesSent()
        break
      default:
        directMessages = twitter.directMessageOperations().getDirectMessagesReceived()
        break
    }
    render view: SpringSocialTwitterUtils.config.twitter.page.directMessages, model: ['directMessages': directMessages, 'dmListType': dmListType]
  }

  def trends = {
    def trends = twitter.searchOperations().getCurrentTrends()
    render view: SpringSocialTwitterUtils.config.twitter.page.trends, model: ['trends': trends]
  }

  def tweet = {
    def message = params.message
    twitter.timelineOperations().updateStatus(message)
    redirect(action: timeline, params: [id: 'user'])
  }

  def search = {
    def query = params.query
    def tweets = twitter.searchOperations().search(query).getTweets()
    flash.message = "Search result for '${query}'"
    render view: SpringSocialTwitterUtils.config.twitter.page.timeLine, model: ['timeline': tweets]
  }

  def login = {
    render(view: SpringSocialTwitterUtils.config.twitter.page.connect)
  }

  def auth() {
    if (!isConnected()) {
      redirect(action: 'login')
      return false
    }
  }

  Boolean isConnected() {
    connectionRepository.findPrimaryConnection(Twitter)
  }

}

grails-app/views/layouts/twitterLayout.gsp
<!DOCTYPE html>
<html>
<head>
    <title>Grails Spring Social Twitter Plugin - <g:layoutTitle default="Grails"/></title>
    <link rel="stylesheet" href="${resource(dir: 'css/springsocial', file: 'page.css', plugin: 'spring-social-core')}"/>
    <link rel="stylesheet" href="${resource(dir: 'css/springsocial', file: 'form.css', plugin: 'spring-social-core')}"/>
    <link rel="stylesheet" href="${resource(dir: 'css/springsocial', file: 'twitter.css', plugin: 'spring-social-twitter')}"/>
    <g:layoutHead/>
</head>

<body>
<div id="header">
    <h1>Grails Spring Social Twitter Plugin !</h1>
</div>

  <div id="left">
    <div id="leftNav">
        <g:render template="/springsocial/twitter/twitterMenu"/>
    </div>
  </div>

  <div id="right">
  <div id="content">
      <g:layoutBody/>
  </div>
  </div>

</body>
</html>

grails-app/views/springsocial/twitter/_anywhere.gsp
<script src="http://platform.twitter.com/anywhere.js?id=${twitterAnywhereApiKet}&v=1" type="text/javascript"></script>
<script type="text/javascript">
    twttr.anywhere(function (T) {
        T(".feed").linkifyUsers();
    });
</script>

grails-app/views/springsocial/twitter/_menu.gsp
<g:render template="/springsocial/twitter/twitterMenu" plugin="spring-social-twitter" />

grails-app/views/springsocial/twitter/_twitterMenu.gsp
<div id="network"><g:link controller="springSocialTwitter">Twitter</g:link></div>

<ul class="menu">
    <li><g:link controller="springSocialTwitter">User Profile</g:link></li>
    <li><g:link controller="springSocialTwitter" action="timeline">Timeline</g:link></li>
    <li><g:link controller="springSocialTwitter" action="profiles" id="friends">Friends</g:link></li>
    <li><g:link controller="springSocialTwitter" action="profiles" id="followers">Followers</g:link></li>
    <li><g:link controller="springSocialTwitter" action="messages">Messages</g:link></li>
    <li><g:link controller="springSocialTwitter" action="trends">Current Trends</g:link></li>
</ul>

grails-app/views/springsocial/twitter/connect.gsp
<html>
<head>
    <title>Connect to Twitter</title>
    <meta name='layout' content='twitterLayout'/>
</head>

<body>
<h1>Connect to Twitter</h1>


<g:form mapping="springSocialConnect" params="[providerId: 'twitter']" method="POST">
    <div class="formInfo">
        <p>
            You haven't created any connections with Twitter yet. Click the button to connect Spring Social Showcase with your Twitter account.
            (You'll be redirected to Twitter where you'll be asked to authorize the connection.)
        </p>
    </div>

    <p><button type="submit"><img
            src="${createLinkTo(dir: 'images/springsocial/twitter', file: 'connect-with-twitter.png')}"/></button></p>

%{--<label for="postTweet"><g:checkBox id="postTweet"
name="${grailsApplication.config.twitter.postTweetFlag}"/> Post a tweet about connecting with Grails Social Showcase</label>--}%
</g:form>

</body>
</html>

grails-app/views/springsocial/twitter/connected.gsp
<html>
<head>
    <title>Connected to Twitter</title>
    <meta name='layout' content='twitterLayout' />
</head>
<body>
<h1>Connected to Twitter</h1>

<form action="${createLink(controller: 'connect', params: [providerId: 'twitter'])}" id="disconnect" method="post">
    <input type="hidden" name="_method" value="delete"/>
    <div class="formInfo">
        <p>The Grails Social Showcase sample application is already connected to your Twitter account.
        Click the button if you wish to disconnect.
    </div>

    <button type="submit">Disconnect</button>
</form>

<p><g:link controller="home">Return to home page</g:link></p>

</body>
</html>

grails-app/views/springsocial/twitter/index.gsp
<html>
<head>
    <title>Twitter Profile</title>
    <meta name='layout' content='twitterLayout'/>
</head>

<body>
<h3>Your Twitter Profile</h3>

<p>Hello, ${profile.name}</p>
<img src="${profile.profileImageUrl}"/>
<dl>
    <dt>Twitter ID:</dt>
    <dd>${profile.id}</dd>
    <dt>Screen name:</dt>
    <dd><a href="${profile.profileUrl}" target="_blank">${profile.screenName}</a></dd>
    <dt>Description:</dt>
    <dd>${profile.description}</dd>
    <dt>Location:</dt>
    <dd>${profile.location}</dd>
    <dt>URL:</dt>
    <dd><a href="${profile.url}">${profile.url}</a></dd>
</dl>

<g:form method="DELETE" mapping="springSocialConnect" params="[providerId:'twitter']">
    <button type="submit">Disconnect from Twitter</button>
</g:form>


</body>
</html>

grails-app/views/springsocial/twitter/messages.gsp
<html>
<head>
    <title>Twitter Messages</title>
    <meta name='layout' content='twitterLayout'/>
</head>

<body>

<h3>Your Twitter ${dmListType.capitalize()} Messages</h3>


<g:link controller="springSocialTwitter" action="messages" id="inbox">Messages</g:link>

<g:form controller="springSocialTwitter" action="sendDM" method="POST">
    <p>Send a message:</p>
    <label for="to">To:</label><g:textField name="to"/><br/>
    <g:textArea name="text" rows="2" cols="80"></g:textArea><br/>
    <g:submitButton name="submit" value="Send Message"/>
</g:form>

<g:link controller="springSocialTwitter" action="messages" id="inbox">Messages</g:link>

    <ul class="choices">
    <li><g:link controller="springSocialTwitter" action="messages" id="received">Inbox</g:link></li>
    <li><g:link controller="springSocialTwitter" action="messages" id="sent">Send</g:link></li>
    </ul>


    <div class="feed">
        <ul class="imagedList">
            <g:each in="${directMessages}" var="dm">
                <li class="imagedItem">
                    <div class="image">
                        <g:if test="${dm.sender.profileImageUrl}">
                            <img src="${dm.sender.profileImageUrl}" alt="" align="left" />
                        </g:if>
                    </div>

                    <div class="content">
                        <strong><a href="${dm.sender.url}">${dm.sender.screenName}</a></strong><br/>
                        <span class="dmRecipient">to ${dm.recipient.screenName}"</span><br/>
                        ${dm.text}<br/>
                        <span class="postTime">${dm.createdAt}</span>
                    </div>
                </li>
            </g:each>

        </ul>
    </div>

    </body>
    </html>

grails-app/views/springsocial/twitter/profiles.gsp
<html>
<head>
    <title>Twitter Profiles</title>
    <meta name='layout' content='twitterLayout'/>
</head>

<body>

<h3>Your Twitter Friends</h3>

<ul class="imagedList">
    <g:each in="${profiles}" var="profile">
        <li class="imagedItem">
            <div class="image">
                <g:if test="${profile.profileImageUrl}">
                    <img src="${profile.profileImageUrl}" alt="" width="48" height="48" align="left" />
                </g:if>
            </div>

            <div class="content">
                <p><a href="http://twitter.com/${profile.screenName}">${profile.screenName}</a></p>
            </div>
        </li>
    </g:each>

</ul>

</body>
</html>

grails-app/views/springsocial/twitter/timeline.gsp
<html>
<head>
    <title>Twitter TimeLine</title>
    <meta name='layout' content='twitterLayout'/>
</head>

<body>

<g:if test="${flash.message}">
    <h3>${flash.message}</h3>
</g:if>
<g:else>
    <h3>Your Twitter ${timelineName} Timeline</h3>
</g:else>



<h4>Post a tweet</h4>

<g:form controller="springSocialTwitter" action="tweet" name="sendMessage">
    <g:textArea name="message" rows="2" cols="80" />
    <g:submitButton name="submit" value="Send Tweet"/>
</g:form>


<g:form controller="springSocialTwitter" action="search" name="search">
    <g:textField name="query"/><br/>
    <g:submitButton name="submit" value="Search"/>
</g:form>

<ul class="choices">
    <li><g:link controller="springSocialTwitter" action="timeline" id="home">Home Timeline</g:link></li>
    <li><g:link controller="springSocialTwitter" action="timeline" id="user">User Timeline</g:link></li>
    <li><g:link controller="springSocialTwitter" action="timeline" id="public">Public Timeline</g:link></li>
    <li><g:link controller="springSocialTwitter" action="timeline" id="mentions">Mentions</g:link></li>
    <li><g:link controller="springSocialTwitter" action="timeline" id="favorites">Favorites</g:link></li>
</ul>

<div class="feed">
    <ul class="imagedList">
        <g:each in="${timeline}" var="tweet">
            <li class="imagedItem">
                <div class="image">
                    <g:if test="${tweet.profileImageUrl}">
                        <img src="${tweet.profileImageUrl}" align="left"/>
                    </g:if>
                </div>

                <div class="content">
                    <strong><a href="http://twitter.com/${tweet.fromUser}">${tweet.fromUser}</a></strong><br/>
                    ${tweet.text}<br/>
                    <span class="postTime">${tweet.createdAt}</span>
                </div>
            </li>
        </g:each>

    </ul>
</div>

</body>
</html>

grails-app/views/springsocial/twitter/trends.gsp
<html>
<head>
    <title>Twitter Trending Topics</title>
    <meta name='layout' content='twitterLayout'/>
</head>

<body>

<h3>Trending Topics</h3>

<ul class="imagedList">
    <g:each in="${trends.trends}" var="trend">
        <li class="imagedItem">
            <div class="content">
                <p>${trend.query}</p>
            </div>
        </li>
    </g:each>

</ul>

</body>
</html>